# Generated by Django 3.2.16 on 2023-09-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Knowledge', models.CharField(max_length=128, verbose_name='知识')),
                ('Content', models.CharField(max_length=256, verbose_name='内容')),
            ],
            options={
                'db_table': 'backend_knowledge',
            },
        ),
    ]
